# Generated by Django 2.1.5 on 2019-02-08 23:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('hora_ir_a_comer', models.DateTimeField(default=django.utils.timezone.now)),
                ('hora_regresar_comer', models.DateTimeField(default=datetime.datetime(2019, 2, 9, 0, 33, 23, 430842, tzinfo=utc))),
                ('hora_salida', models.DateTimeField(default=datetime.datetime(2019, 2, 9, 7, 33, 23, 430877, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=30)),
                ('cargo', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='asistencia',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAsistencia.Usuario'),
        ),
    ]
