# Generated by Django 2.1.5 on 2019-02-09 22:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appAsistencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='hora_regresar_comer',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 9, 23, 4, 32, 264161, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='hora_salida',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 10, 6, 4, 32, 264280, tzinfo=utc)),
        ),
    ]
